name: Ambience
options:
    bundleIdPrefix: com.CodingKovs.Ambience
deploymentTarget: '16.0'
settings:
    MARKETING_VERSION: 4.0
targets:
  ioslk:
    type: application
    platform: iOS
    deploymentTarget: '16.0'
    sources: [Ambience]
    settings:
      base:
        INFOPLIST_FILE: Ambience/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.CodingKovs.Ambience
        ENABLE_USER_SCRIPT_SANDBOXING: false
        ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
        MY_SETTING: platform ${platform}

    
